from typing import List
from sqlalchemy.ext.asyncio import AsyncSession
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select

from src.auth.dependencies import get_current_user
from src.auth.models import User
from src.shared.database import get_async_db
from src.tasks.models import Task
from src.tasks.schemas import TaskCreate, TaskResponse


router = APIRouter(prefix='/tasks', tags=["task"])


@router.post("/", status_code=status.HTTP_201_CREATED, response_model=TaskResponse)
async def create_task(
    payload: TaskCreate,
    current_user: User = Depends(get_current_user), 
    db: AsyncSession = Depends(get_async_db)
    ):
    task = Task(
        title=payload.title, 
        description=payload.description, 
        owner_id = current_user.id)
    
    db.add(task)
    await db.commit()
    await db.refresh(task) # populate autogenerated fields like id, created_at
    return task

@router.get("/", response_model=List[TaskResponse])
async def get_task(
    current_user: User = Depends(get_current_user), 
    db: AsyncSession = Depends(get_async_db)
    ):
    stmt = select(Task).where(Task.owner_id == current_user.id)
    result = await db.execute(stmt)
    return result.scalars().all()