from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select

from .models import User
from .schemas import UserCreate, UserResponse
from .utils import get_password
from ..shared.dependencies import get_async_db
from sqlalchemy.ext.asyncio import AsyncSession

router = APIRouter(prefix="/auth", tags=["Auth"])

@router.post('/register', status_code=201, response_model=UserResponse)
async def createUser(payload: UserCreate, db : AsyncSession = Depends(get_async_db)):
    hashed = get_password(password=payload.password)
    
    # check duplicate
    stmt = select(User).where(User.email == payload.email)
    res = await db.execute(stmt)
    existing = res.scalar_one_or_none()
    
    if existing:
        raise HTTPException(status_code=400, detail="Email already registered")
    
    # Hash Password
    user = User(email= payload.email, hashed_password=hashed)
    
    db.add(user)
    await db.commit()
    await db.refresh(user) # populate autogenerated fields like id, created_at
    return user